export const MOCK_PROFILES = [
  {
    id: "mock-1",
    nome: "Domina Hera",
    localizacao: "São Paulo, SP",
    lat: -23.5505,
    lng: -46.6333,
    is_premium: true,
    status: "approved",
    bio: "Especialista em bondage e dominação psicológica. Com mais de 10 anos de experiência no universo BDSM.",
    servicos: ["Bondage", "Foot Worship", "Sissy Training"],
    preco_min: 300,
    preco_max: 1500,
  },
  {
    id: "mock-2",
    nome: "Mistress Valentina",
    localizacao: "Rio de Janeiro, RJ",
    lat: -22.9068,
    lng: -43.1729,
    is_premium: true,
    status: "approved",
    bio: "Fetiche em couro e látex. Sessões personalizadas em ambiente discreto e luxuoso na Barra da Tijuca.",
    servicos: ["Leather", "Spanking", "Roleplay"],
    preco_min: 400,
    preco_max: 2000,
  },
  {
    id: "mock-3",
    nome: "Lady Morgana",
    localizacao: "Brasília, DF",
    lat: -15.7975,
    lng: -47.8919,
    is_premium: true,
    status: "approved",
    bio: "Dominação clássica e rigorosa. Foco em disciplina e etiqueta. Atendimento exclusivo no Lago Sul.",
    servicos: ["CBT", "Pegging", "Medical Play"],
    preco_min: 500,
    preco_max: 3000,
  },
  {
    id: "mock-4",
    nome: "Domina Safira",
    localizacao: "Salvador, BA",
    lat: -12.9714,
    lng: -38.5014,
    is_premium: true,
    status: "approved",
    bio: "Exploração sensorial e impacto. Uma experiência única de entrega e descoberta na capital baiana.",
    servicos: ["Impact Play", "Wax Play", "Sensory Deprivation"],
    preco_min: 250,
    preco_max: 1200,
  },
  {
    id: "mock-5",
    nome: "Mistress Elena",
    localizacao: "Curitiba, PR",
    lat: -25.429,
    lng: -49.2671,
    is_premium: false,
    status: "approved",
    bio: "Iniciante no portal, mas com vasta experiência em submissão masculina e feminização.",
    servicos: ["Feminização", "Humilhação Verbal"],
    preco_min: 200,
    preco_max: 800,
  },
  {
    id: "mock-6",
    nome: "Domina Kyra",
    localizacao: "Belo Horizonte, MG",
    lat: -19.9167,
    lng: -43.9345,
    is_premium: false,
    status: "approved",
    bio: "Foco em adoração e servidão. Transforme-se no que eu desejar.",
    servicos: ["Worship", "Financial Domination"],
    preco_min: 350,
    preco_max: 1800,
  },
  {
    id: "mock-7",
    nome: "Lady Raven",
    localizacao: "Porto Alegre, RS",
    lat: -30.0346,
    lng: -51.2177,
    is_premium: true,
    status: "approved",
    bio: "Atmosfera gótica e dominação sombria. Especialista em jogos de poder intensos.",
    servicos: ["Gothic BDSM", "Breath Play", "Edge Play"],
    preco_min: 450,
    preco_max: 2500,
  },
  {
    id: "mock-8",
    nome: "Mistress Jade",
    localizacao: "Fortaleza, CE",
    lat: -3.7172,
    lng: -38.5433,
    is_premium: false,
    status: "approved",
    bio: "Dominação suave para iniciantes e curiosos. Venha descobrir seus limites com segurança.",
    servicos: ["Light BDSM", "Bondage Soft"],
    preco_min: 150,
    preco_max: 600,
  }
];