export const MOCK_PROFILES = [
  {
    id: "mock-1",
    nome: "Domina Hera",
    localizacao: "São Paulo, SP",
    bio: "Profissional experiente com 5 anos de atuação.",
    servicos: ["Bondage", "Spanking", "Roleplay"],
    fotos: [],
    foto_url: null,
    is_premium: true,
    status: "approved",
    lat: -23.5505,
    lng: -46.6333,
  },
  {
    id: "mock-2",
    nome: "Mistress Kali",
    localizacao: "Rio de Janeiro, RJ",
    bio: "Dominatrix sofisticada e discreta.",
    servicos: ["CBT", "Foot Worship", "Wax Play"],
    fotos: [],
    foto_url: null,
    is_premium: true,
    status: "approved",
    lat: -22.9068,
    lng: -43.1729,
  },
  {
    id: "mock-3",
    nome: "Lady Serpente",
    localizacao: "Belo Horizonte, MG",
    bio: "Especialista em sensory deprivation e medical play.",
    servicos: ["Medical Play", "Sensory Deprivation", "Pegging"],
    fotos: [],
    foto_url: null,
    is_premium: false,
    status: "approved",
    lat: -19.9167,
    lng: -43.9345,
  },
  {
    id: "mock-4",
    nome: "Domina Vênus",
    localizacao: "Curitiba, PR",
    bio: "Dominação financeira e humilhação verbal.",
    servicos: ["Dominação Financeira", "Humilhação Verbal", "Sissy Training"],
    fotos: [],
    foto_url: null,
    is_premium: true,
    status: "approved",
    lat: -25.4284,
    lng: -49.2733,
  },
];